[build]
  # No build command needed for static site
  publish = "."

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache HTML files for 1 hour
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect rules for SPA behavior (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  
# Form handling (for future backend integration)
[build.environment]
  NODE_VERSION = "18"